### ISSUE TITLE
ModAPI is on wrong Server Version

### ISSUE THREAD

**Issue by svg-frog** [5zig/The-5zig-Mod-API-2.0#1]
The 5ZigServerModAPI is currently programmed using 1_8_R1 NMS data - however, the mod itself uses version 1.8.3, leading users to believe that server version 1.8.3 (R2) is necessary to run. Additional checks/hooks should be made for running on 1_8_R1 and 1_8_R2.

Log from Server Console: http://pastebin.com/KMYjMP5g

**Comment by 5zig** [comment]
Hey, thanks for the suggestions.
Hooks for both 1_8_R1 and 1_8_R2 have been added.
